import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex bg-green-bg">
        <SideBar />
        <div className="bg-white p-7 w-full rounded-3xl">{children}</div>
      </body>
    </html>
  );
}
